services:
  orchestrator:
    build:
      dockerfile: Dockerfile-orchestrator
    env_file:
      - path: ./configs/.env
        required: true
    environment:
      ORCHESTRATOR_HOST: 0.0.0.0
    ports:
      - "${ORCHESTRATOR_PORT}:${ORCHESTRATOR_PORT}"
  agent:
    build:
      dockerfile: Dockerfile-agent
    depends_on:
      - orchestrator
    env_file:
      - path: ./configs/.env
        required: true
    environment:
      ORCHESTRATOR_HOST: orchestrator
