// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.2
// source: internal/transport/grpc/proto/orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result float32 `protobuf:"fixed32,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_internal_transport_grpc_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TaskResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResult) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type IncomingTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          string `protobuf:"bytes,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          string `protobuf:"bytes,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     string `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime uint64 `protobuf:"varint,5,opt,name=operationTime,proto3" json:"operationTime,omitempty"`
}

func (x *IncomingTask) Reset() {
	*x = IncomingTask{}
	mi := &file_internal_transport_grpc_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingTask) ProtoMessage() {}

func (x *IncomingTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingTask.ProtoReflect.Descriptor instead.
func (*IncomingTask) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *IncomingTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IncomingTask) GetArg1() string {
	if x != nil {
		return x.Arg1
	}
	return ""
}

func (x *IncomingTask) GetArg2() string {
	if x != nil {
		return x.Arg2
	}
	return ""
}

func (x *IncomingTask) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *IncomingTask) GetOperationTime() uint64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

var File_internal_transport_grpc_proto_orchestrator_proto protoreflect.FileDescriptor

var file_internal_transport_grpc_proto_orchestrator_proto_rawDesc = []byte{
	0x0a, 0x30, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0a, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x8a, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x4f, 0x0a, 0x13,
	0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x63, 0x6f, 0x6d,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a,
	0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_transport_grpc_proto_orchestrator_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_orchestrator_proto_rawDescData = file_internal_transport_grpc_proto_orchestrator_proto_rawDesc
)

func file_internal_transport_grpc_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_transport_grpc_proto_orchestrator_proto_rawDescData)
	})
	return file_internal_transport_grpc_proto_orchestrator_proto_rawDescData
}

var file_internal_transport_grpc_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_grpc_proto_orchestrator_proto_goTypes = []any{
	(*TaskResult)(nil),   // 0: proto.TaskResult
	(*IncomingTask)(nil), // 1: proto.IncomingTask
}
var file_internal_transport_grpc_proto_orchestrator_proto_depIdxs = []int32{
	0, // 0: proto.OrchestratorService.GetTasks:input_type -> proto.TaskResult
	1, // 1: proto.OrchestratorService.GetTasks:output_type -> proto.IncomingTask
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_orchestrator_proto_init() }
func file_internal_transport_grpc_proto_orchestrator_proto_init() {
	if File_internal_transport_grpc_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_transport_grpc_proto_orchestrator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_orchestrator_proto = out.File
	file_internal_transport_grpc_proto_orchestrator_proto_rawDesc = nil
	file_internal_transport_grpc_proto_orchestrator_proto_goTypes = nil
	file_internal_transport_grpc_proto_orchestrator_proto_depIdxs = nil
}
